---
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    hikari:
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

  flyway:
    enabled: true
    url: jdbc:h2:mem:testdb
    user: sa
    password: password

springdoc:
  swagger-ui:
    path: /