
name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      env:
        DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
        GITHUB_CI_USERNAME: halvorot
        GITHUB_CI_PASSWORD: ${{ secrets.GITHUB_TOKEN}}
      run: mvn compile jib:build
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ${{ github.workspace }}/build/reports/jacoco/testCoverage/testCoverage.xml
